### ISSUE TITLE
Warning: FirebaseRef.auth() being deprecated

### ISSUE THREAD

**Issue by vergissberlin** [Rigidflame/firebase-login#3]
After fixing CLI-Version-Bug #2  I got this warning message:
**Stack**

``` bash
FIREBASE WARNING: FirebaseRef.auth() being deprecated. Please use FirebaseRef.authWithCustomToken() instead. 

Error: Firebase.auth failed: First argument must be a valid credential (a string).
    at Error (<anonymous>)
    at Yb (/var/www/test/fireTest/node_modules/firebase/lib/firebase-node.js:35:313)
    at P.Q.Q (/var/www/test/fireTest/node_modules/firebase/lib/firebase-node.js:233:337)
    at Request._callback (/var/www/test/fireTest/node_modules/firebase-login/index.js:28:17)
    at Request.self.callback (/var/www/test/fireTest/node_modules/firebase-login/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/test/fireTest/node_modules/firebase-login/node_modules/request/request.js:978:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/test/fireTest/node_modules/firebase-login/node_modules/request/request.js:929:12)
    at IncomingMessage.emit (events.js:117:20)
```

You can generate a token like this:

``` javascript
// Generate a new secure JWT
var FirebaseTokenGenerator = require("firebase-token-generator");
var tokenGenerator = new FirebaseTokenGenerator('Uleo4JckSg0mmqRltAABBCC');
var token = tokenGenerator.createToken({uid: "1"});

console.log(token);

var Firebase = require("firebase");
var ref = new Firebase("https://<YOUR-ID>.firebaseio.com");
ref.authWithCustomToken(token, function(error, authData) {
    if (error) {
        console.log("Login Failed!", error);
    } else {
        console.log("Login Succeeded!", authData);
    }
});
```

**Comment by abeisgoat** [comment]
Fixed, thanks!
